### ISSUE TITLE
About trainable parameter t

### ISSUE THREAD

**Issue by irsLu** [zju-vipa/MEAT-TIL#3]
The paper says “The initial weights of **_t_** are independently sampled from distribution Uniform(-γ, γ), where γ > 0 is a hyperparameter.”  
So the question I'm wondering is if **_t_** is negative, then won't there be a problem with log(**_t_**) in the equation 6?
<img width="361" alt="image" src="https://user-images.githubusercontent.com/42465965/185773716-6d644806-8d3f-40b4-b0a1-0b8dedb3576b.png">

**Comment by zhl98** [comment]
Hello, has this problem been solved?  If t is negative， log(t) will not be calculated.
